hw8
Ducanhnguyen18/daividcute1805 pull request #7
Opened 2022-05-01 04:40 UTC by Ducanhnguyen18

@dmitrii-kruglov

2022-05-01 05:13 UTC, closed without merging

2022-05-01 05:15 UTC, Ducanhnguyen18 commented
дз последние два файлы hw28.04--1 и  hw28.04--2

2022-05-01 11:23 UTC, dmitrii-kruglov requested changes
Нужно доделать. Не закрывайте pull request, пусть остаётся открытым. К тому же очень прошу Вас разные домашние задание делать в разных pull request

2022-05-01 11:23 UTC, dmitrii-kruglov commented on hw28.04--2.cpp
> +catch(const string str)
это нужно вынести в main

2022-05-01 11:23 UTC, dmitrii-kruglov commented on hw28.04--2.cpp
> +bool request(string login, string user_login, string user_password)
правильные логин и пароль не должны передаваться в эту функцию

2022-05-01 11:23 UTC, dmitrii-kruglov commented on hw28.04--1.cpp
> +throw second;
в этой задаче не надо было создавать собственное исключение, необходимо просто обработать системное

2022-05-03 18:23 UTC, Ducanhnguyen18 commented on hw28.04--1.cpp
> +throw second;
Система не бросает исключение при делении на 0

2022-05-03 20:01 UTC, dmitrii-kruglov commented on hw28.04--1.cpp
> +throw second;
Да, хорошо, этот комментарий можно не исправлять

2022-05-03 22:04 UTC, Ducanhnguyen18 commented on hw28.04--1.cpp
> +throw second;
я так понимаю что,1-е  зачтено, а второе исправлять надо.

2022-05-03 22:04 UTC, dmitrii-kruglov commented on hw28.04--1.cpp
> +throw second;
совершенно верно